import type { Metadata } from "next";


import "./globals.css";
import clsx from "clsx";
import { comfortaa } from "./ui/fonts";
import localFont from 'next/font/local'
 
const myFont = localFont({
  src: './ui/MarckScript-Regular.ttf',
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
